export const instagramData = [
  {
    name: "CNN To Permanently Close Its Doors As Ratings Plunge 30 Percent",
    number_of_posts: 101,
    percentage_fake: 1,
    spreaders: "COM 1",
    victims: "COM 4",
    ideology: "Progressive Left",
  },
  {
    name: "Eric Trump: It would be 'foolish' for my dad to release tax returns",
    number_of_posts: 194,
    percentage_fake: 11,
    spreaders: "COM 3",
    victims: "COM 5",
    ideology: "Progressive Left",
  },
  {
    name: "BREAKING! Roy Mooreâ€™s Accuser Worked for Democratic Leaders and Is Actively Campaigning for Mooreâ€™s Opponent â‹† Activist Mommy",
    number_of_posts: 500,
    percentage_fake: 8,
    spreaders: "COM 4",
    victims: "COM 1",
    ideology: "Progressive Left",
  },
  {
    name: "Kurt Russel Just SHOWED Overpaid Celebs Itâ€™s Time To Shut Up About Trump â€“ Hits Them Where It Hurts!",
    number_of_posts: 350,
    percentage_fake: 20,
    spreaders: "COM 1",
    victims: "COM 5",
    ideology: "Progressive Left",
  },
  {
    name: "BREAKING: 60 People Just Found Dead In Ohio",
    number_of_posts: 150,
    percentage_fake: 12,
    spreaders: "COM 8",
    victims: "COM 6",
    ideology: "Conservative",
  },
  {
    name: "Denzel Washington: With Trump we avoided war with Russia and Orwellian Police State",
    number_of_posts: 250,
    percentage_fake: 3,
    spreaders: "COM 11",
    victims: "COM 6",
    ideology: "Conservative",
  },
  {
    name: "Oprah Winfrey: The Butler, racism and Obama",
    number_of_posts: 450,
    percentage_fake: 5,
    spreaders: "COM 14",
    victims: "COM 3",
    ideology: "Progressive Left",
  },
  {
    name: "USA: Mysterious Nazi submarine from WWII discovered in Great Lakes!",
    number_of_posts: 320,
    percentage_fake: 10,
    spreaders: "COM 16",
    victims: "COM 7",
    ideology: "Progressive Left",
  },
  {
    name: "Computer Models Show IRMA Destroying New York City On Sept. 10",
    number_of_posts: 180,
    percentage_fake: 8,
    spreaders: "COM 18",
    victims: "COM 8",
    ideology: "Progressive Left",
  },
  {
    name: "NASA Will Pay You $100,000 To Stay In Bed For 60 Days!",
    number_of_posts: 700,
    percentage_fake: 2,
    spreaders: ".COM 21",
    victims: "COM 3",
    ideology: "Progressive Left",
  },
  {
    name: "BREAKING: President Trump Pardons Kim Davis",
    number_of_posts: 1000,
    percentage_fake: 10,
    spreaders: "COM8",
    victims: "COM 6",
    ideology: "Progressive Left",
  },
  {
    name: "Last in Queen Elizabeth II's line of corgis dies, says British press",
    number_of_posts: 800,
    percentage_fake: 5,
    spreaders: "COM 9",
    victims: "COM 3",
    ideology: "Conservative",
  },
  {
    name: "Alabama football Crimson Tide disqualified from national championship",
    number_of_posts: 450,
    percentage_fake: 8,
    spreaders: "COM 12",
    victims: "COM 9",
    ideology: "Conservative",
  },
  {
    name: "Georgia Mosque KEEPS Hurricane Harvey Donations, Will Send To Syrian Refugees Instead",
    number_of_posts: 550,
    percentage_fake: 12,
    spreaders: "COM 14",
    victims: "COM 11",
    ideology: "Progressive Left",
  },
  {
    name: "World's most popular candy to be removed from shelves by October 2017!",
    number_of_posts: 300,
    percentage_fake: 6,
    spreaders: "COM 20",
    victims: "COM 11",
    ideology: "Conservative",
  },
];
