export const redditData = [
  {
    name: "notchoosy1921",
    number_of_posts: 101,
    percentage_fake: 1,
    spreaders: "COM 1",
    victims: "COM 4",
    ideology: "Progressive Left",
  },
  {
    name: "AaronSorkin",
    number_of_posts: 194,
    percentage_fake: 11,
    spreaders: "COM 3",
    victims: "COM 5",
    ideology: "Progressive Left",
  },
  {
    name: "lwtprettylaugh",
    number_of_posts: 500,
    percentage_fake: 8,
    spreaders: "COM 4",
    victims: "COM 1",
    ideology: "Progressive Left",
  },
  {
    name: "douggarland",
    number_of_posts: 350,
    percentage_fake: 20,
    spreaders: "COM 1",
    victims: "COM 5",
    ideology: "Progressive Left",
  },
  {
    name: "WilfordGemma",
    number_of_posts: 150,
    percentage_fake: 12,
    spreaders: "COM 8",
    victims: "COM 6",
    ideology: "Conservative",
  },
  {
    name: "monroevicious",
    number_of_posts: 250,
    percentage_fake: 3,
    spreaders: "COM 11",
    victims: "COM 6",
    ideology: "Conservative",
  },
  {
    name: "Shutterstock",
    number_of_posts: 450,
    percentage_fake: 5,
    spreaders: "COM 14",
    victims: "COM 3",
    ideology: "Progressive Left",
  },
  {
    name: "RobinMeske",
    number_of_posts: 320,
    percentage_fake: 10,
    spreaders: "COM 16",
    victims: "COM 7",
    ideology: "Progressive Left",
  },
  {
    name: "pigzilla_",
    number_of_posts: 180,
    percentage_fake: 8,
    spreaders: "COM 18",
    victims: "COM 8",
    ideology: "Progressive Left",
  },
  {
    name: "GabrieleNeher",
    number_of_posts: 700,
    percentage_fake: 2,
    spreaders: ".COM 21",
    victims: "COM 3",
    ideology: "Progressive Left",
  },
  {
    name: "Twitter User",
    number_of_posts: 1000,
    percentage_fake: 10,
    spreaders: "COM8",
    victims: "COM 6",
    ideology: "Progressive Left",
  },
  {
    name: "Twitter User2",
    number_of_posts: 800,
    percentage_fake: 5,
    spreaders: "COM 9",
    victims: "COM 3",
    ideology: "Conservative",
  },
  {
    name: "Twitter User3",
    number_of_posts: 450,
    percentage_fake: 8,
    spreaders: "COM 12",
    victims: "COM 9",
    ideology: "Conservative",
  },
  {
    name: "Twitter User4",
    number_of_posts: 550,
    percentage_fake: 12,
    spreaders: "COM 14",
    victims: "COM 11",
    ideology: "Progressive Left",
  },
  {
    name: "Twitter User5",
    number_of_posts: 300,
    percentage_fake: 6,
    spreaders: "COM 20",
    victims: "COM 11",
    ideology: "Conservative",
  },
];
