export const twitterUserData = [
  {
    name: "sheezy0",
    views_posted: "1.2k",
    activity_on_posts: 5,
    fake_news: "42.3%",
  },
  {
    name: "DavdBurnett",
    views_posted: "1.1k",
    activity_on_posts: 15,
    fake_news: "61.4%",
  },
  {
    name: "lwtprettylaugh",
    views_posted: "2.3k",
    activity_on_posts: 8,
    fake_news: "73.1%",
  },
  {
    name: "douggarland",
    views_posted: "3.1k",
    activity_on_posts: 20,
    fake_news: "58.4%",
  },
  {
    name: "WilfordGemma",
    views_posted: "1.3k",
    activity_on_posts: 12,
    fake_news: "78.4%",
  },
  {
    name: "monroevicious",
    views_posted: "1.7k",
    activity_on_posts: 3,
    fake_news: "54.5%",
  },
  {
    name: "Shutterstock",
    views_posted: "1.5k",
    activity_on_posts: 5,
    fake_news: "31.2%",
  },
  {
    name: "RobinMeske",
    views_posted: "1.4k",
    activity_on_posts: 10,
    fake_news: "80.3%",
  },
  {
    name: "pigzilla_",
    views_posted: "2.5k",
    activity_on_posts: 8,
    fake_news: "73.2%",
  },
  {
    name: "GabrieleNeher",
    views_posted: "2.3k",
    activity_on_posts: 2,
    fake_news: "31.3%",
  },
  {
    name: "Twitter User",
    views_posted: "1.7k",
    activity_on_posts: 10,
    fake_news: "48.53%",
  },
  {
    name: "Twitter User2",
    views_posted: "1.5k",
    activity_on_posts: 5,
    fake_news: "68.43%",
  },
  {
    name: "Twitter User3",
    views_posted: "1.9k",
    activity_on_posts: 8,
    fake_news: "87.89%",
  },
  {
    name: "Twitter User4",
    views_posted: "2.0k",
    activity_on_posts: 12,
    fake_news: "56.23%",
  },
  {
    name: "Twitter User5",
    views_posted: "2.8k",
    activity_on_posts: 6,
    fake_news: "89.01%",
  },
];
