export const twitterUserData = [
  {
    name: "kunal",
    views_posted: "8.2k",
    retweets: "1.3k",
    comments: "0.8k",
    fake_news: "42.3%",
  },
  {
    name: "DavdBurnett",
    views_posted: "4.1k",
    retweets: "1.3k",
    comments: "0.8k",
    fake_news: "61.4%",
  },
  {
    name: "TanishqKapoor",
    views_posted: "5.3k",
    retweets: "1.5k",
    comments: "1k",
    fake_news: "73.1%",
  },
  {
    name: "Rajat",
    views_posted: "10.1k",
    retweets: "2.5k",
    comments: "1.6k",
    fake_news: "58.4%",
  },
  {
    name: "Yashika",
    views_posted: "7.56k",
    retweets: "1.3k",
    comments: "1.36k",
    fake_news: "78.4%",
  },
  {
    name: "AkashSen",
    views_posted: "14.7k",
    retweets: "5.6k",
    comments: "4.5k",
    fake_news: "54.5%",
  },
  {
    name: "RozeetaFernandes",
    views_posted: "9.5k",
    retweets: "5.6k",
    comments: "2.6k",
    fake_news: "31.2%",
  },
  {
    name: "Sakina",
    views_posted: "15.4k",
    retweets: "8.9k",
    comments: "5.6k",
    fake_news: "80.3%",
  },
  {
    name: "Sammeer",
    views_posted: "20.5k",
    retweets: "5.6k",
    comments: "4.5k",
    fake_news: "73.2%",
  },
  {
    name: "Samuel",
    views_posted: "12.3k",
    retweets: "5.45k",
    comments: "2.10k",
    fake_news: "31.3%",
  },
];
