export const twitterData = [
  {
    name: "Barack Obama ARRESTED",
    number_of_posts: 100,
    percentage_fake: 5,
    spreaders: "COM 1",
    victims: "COM 4",
    ideology: "Progressive Left",
  },
  {
    name: "Mar-A-Lago Destroyed ",
    number_of_posts: 200,
    percentage_fake: 15,
    spreaders: "COM 2",
    victims: "COM 6",
    ideology: "Progressive Left",
  },
  {
    name: "78 Year Old CIA Agent",
    number_of_posts: 500,
    percentage_fake: 8,
    spreaders: "COM 4",
    victims: "COM 1",
    ideology: "Progressive Left",
  },
  {
    name: "FBI Uncovers Evidence ",
    number_of_posts: 350,
    percentage_fake: 20,
    spreaders: "COM 1",
    victims: "COM 5",
    ideology: "Progressive Left",
  },
  {
    name: "Obama Goes To G20 Summit",
    number_of_posts: 150,
    percentage_fake: 12,
    spreaders: "COM 8",
    victims: "COM 6",
    ideology: "Conservative",
  },
  {
    name: "Kardashians donate whopping sum to Las Vegas",
    number_of_posts: 250,
    percentage_fake: 3,
    spreaders: "COM 11",
    victims: "COM 6",
    ideology: "Conservative",
  },
  {
    name: "White House Chef Quits Because Trump Has Only Eaten Fast Food For 6 Months",
    number_of_posts: 450,
    percentage_fake: 5,
    spreaders: "COM 14",
    victims: "COM 3",
    ideology: "Progressive Left",
  },
  {
    name: "Denzel Washington hit by Facebook fake news story",
    number_of_posts: 320,
    percentage_fake: 10,
    spreaders: "COM 16",
    victims: "COM 7",
    ideology: "Progressive Left",
  },
  {
    name: "Contact Support",
    number_of_posts: 180,
    percentage_fake: 8,
    spreaders: "COM 18",
    victims: "COM 8",
    ideology: "Progressive Left",
  },
  {
    name: "John Kerry Facing Prison",
    number_of_posts: 700,
    percentage_fake: 2,
    spreaders: ".COM 21",
    victims: "COM 3",
    ideology: "Progressive Left",
  },
  {
    name: "Sarah Palin In A Coma After Hit And Run",
    number_of_posts: 1000,
    percentage_fake: 10,
    spreaders: "COM8",
    victims: "COM 6",
    ideology: "Progressive Left",
  },
  {
    name: "Bumble Bee Foods charged after man cooked with tuna",
    number_of_posts: 800,
    percentage_fake: 5,
    spreaders: "COM 9",
    victims: "COM 3",
    ideology: "Conservative",
  },
  {
    name: "Information for the Nation",
    number_of_posts: 450,
    percentage_fake: 8,
    spreaders: "COM 12",
    victims: "COM 9",
    ideology: "Conservative",
  },
  {
    name: "American News is under construction",
    number_of_posts: 550,
    percentage_fake: 12,
    spreaders: "COM 14",
    victims: "COM 11",
    ideology: "Progressive Left",
  },
  {
    name: "Obama Secretly Flees US â€“ Leaves Stunning Evidence Behind",
    number_of_posts: 300,
    percentage_fake: 6,
    spreaders: "COM 20",
    victims: "COM 11",
    ideology: "Conservative",
  },
];
